In [3]:
import pandas as pd

In [4]:
sdata=pd.read_csv("Dataset_Pandas/student.csv")

In [ ]:
#select columns
sdata[ ['firstName','fees',"marks"] ]
#select rows
sdata.loc[sdata.id==106]
sdata.loc[sdata.firstName =='Roshan']
#select rows using  condition
sdata.loc[sdata.age>20]
#slicing -rows
sdata.loc[0:4]
#slicing -rows & columns
sdata.iloc[:6,:4]
sdata.iloc[2:7,1:3]

  firstName  lastName
2     Rohit  Bhandary
3     Nisha   D'Souza
4   Karthik   Poojary
5    Shreya    Shetty
6     Rohan      Naik

In [16]:
sdata["FullName"]= sdata['firstName']+" "+sdata['lastName']
sdata

    id firstName  lastName  age  marks   fees         FullName
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty
1  102    Ananya       Rao   21     92  30000       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty
6  107     Rohan      Naik   21     72  27000       Rohan Naik
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000        Pooja Rai

In [19]:
sdata['age']>20 #boolean
sdata[sdata['age']>20]
sdata_age_filter=sdata[sdata['age']>20]
sdata_age_filter

    id firstName lastName  age  marks   fees         FullName
1  102    Ananya      Rao   21     92  30000       Ananya Rao
4  105   Karthik  Poojary   22     69  32000  Karthik Poojary
6  107     Rohan     Naik   21     72  27000       Rohan Naik
8  109  Abhishek   Kotian   22     64  26000  Abhishek Kotian

In [23]:
sdata_marks_filter=sdata[sdata['marks']>=85] 
sdata.where(sdata['marks']>=85,other="Not Selected")
sdata.loc[sdata['marks']>=85,"Result"]="Selected"
sdata.loc[sdata['marks']<85,"Result"]="Not Selected"
sdata

    id firstName  lastName  age  marks   fees         FullName        Result
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty      Selected
1  102    Ananya       Rao   21     92  30000       Ananya Rao      Selected
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary  Not Selected
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza      Selected
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary  Not Selected
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty      Selected
6  107     Rohan      Naik   21     72  27000       Rohan Naik  Not Selected
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat  Not Selected
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian  Not Selected
9  110     Pooja       Rai   19     90  30000        Pooja Rai      Selected

In [27]:
sdata=pd.read_csv("Dataset_Pandas/student.csv")
#Give 10% Discount to every student
n=int(input())
sdata[f"After {n}% discount "] = sdata['fees']-(sdata['fees']*n)/100
sdata

    id firstName  lastName  age  marks   fees  After 20% discount
0  101    Akshay    Shetty   20     85  25000              20000.0
1  102    Ananya       Rao   21     92  30000              24000.0
2  103     Rohit  Bhandary   19     76  28000              22400.0
3  104     Nisha   D'Souza   20     88  25000              20000.0
4  105   Karthik   Poojary   22     69  32000              25600.0
5  106    Shreya    Shetty   19     95  30000              24000.0
6  107     Rohan      Naik   21     72  27000              21600.0
7  108   Deepika      Bhat   20     81  28000              22400.0
8  109  Abhishek    Kotian   22     64  26000              20800.0
9  110     Pooja       Rai   19     90  30000              24000.0